// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg2lpN-6NCfDg-S2Jead5xGhXm8TEnRRo',
    appId: '1:348588611795:android:5e25abe3d50d3f03ab9c26',
    messagingSenderId: '348588611795',
    projectId: 'arczel-firebase-test',
    storageBucket: 'arczel-firebase-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkq3I8cZNIQbQgg--TOP2u4UYW3QXcrHI',
    appId: '1:348588611795:ios:464ef84ba6c2c334ab9c26',
    messagingSenderId: '348588611795',
    projectId: 'arczel-firebase-test',
    storageBucket: 'arczel-firebase-test.firebasestorage.app',
    androidClientId:
        '348588611795-l3ug9im4j5ctt13r3hskvjc42vq89fp7.apps.googleusercontent.com',
    iosClientId:
        '348588611795-3quhfqncrk8m7qlcd3fn4qgb5baqgg7l.apps.googleusercontent.com',
    iosBundleId: 'com.pahnal.cleanblox',
  );
}
