name: shared
publish_to: none
environment:
   sdk: ^3.8.0
   flutter: 3.32.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter

  core:
    path: ../core
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  dio: ^5.8.0+1

flutter:
  generate: true
    
