name: shared
publish_to: none
environment:
   sdk: ^3.8.0
   flutter: 3.32.0

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7
  core:
    path: ../core
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  logging: ^1.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:
  generate: true
    
