name: feature_auth
publish_to: none
environment:
  sdk: ^3.8.0
  flutter: 3.32.0

dependencies:
  flutter:
    sdk: flutter
  
  core:
    path: ../../core
  shared:
    path: ../../shared
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^15.2.4
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
